Adiciona mock de answers-api
Minhacps/votasp-backend pull request #9
Opened 2018-06-05 01:25 UTC by bwowk

2018-06-08 21:56 UTC, victorperin requested changes

2018-06-08 21:56 UTC, victorperin commented on api-answers/mock/api.yml
> +      questionVersion:
Eu acho que não vai ter necessidade de usar essa versão da resposta.

E mesmo se um dia precisarmos, é fácil implementar isso no futuro.

2018-06-08 21:56 UTC, victorperin commented on api-answers/mock/api.yml
> +  - http
Seria legal colocar:
```
schemes:
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
```

2018-06-08 21:56 UTC, victorperin commented on api-answers/mock/api.yml
> +        - application/json
Seria legal colocar:
```
      produces:
        - application/json
      security:
        - Bearer: []
```

2018-06-08 21:56 UTC, victorperin commented on api-answers/mock/api.yml
> +      #       - 'write:answers'
Podemos remover isso. (não vai ter necessidade de definir acessos)

2018-06-08 21:56 UTC, victorperin commented on api-answers/mock/api.yml
> +      #       - 'write:answers'
Podemos remover isso. (não vai ter necessidade de definir acessos)

2018-06-08 21:56 UTC, victorperin commented on api-answers/mock/api.yml
> +      #       - 'read:answers'
Podemos remover isso. (não vai ter necessidade de definir acessos)

2018-06-08 21:56 UTC, victorperin commented on api-answers/mock/api.yml
> +      #       - 'write:answers'
Podemos remover isso. (não vai ter necessidade de definir acessos)

2018-06-09 13:26 UTC, brunowowk commented on api-answers/mock/api.yml
> +      questionVersion:
Idem para a API de question ou acha que faz sentido deixar por lá?

2018-06-09 13:42 UTC, bwowk commented on api-answers/mock/api.yml
> +      questionVersion:
feito 032675c6e15786bd751f9ece05114702f19ec197

2018-06-09 13:42 UTC, bwowk commented
autenticação trocada para JWT no fe420b1efa7ab3d8127693d48080668fbb69a41d

2018-06-09 14:32 UTC, victorperin commented on api-answers/mock/api.yml
> +      questionVersion:
Valeu @bwowk.
Também acho que faz sentido mudar no question api.

2018-06-09 14:37 UTC, victorperin approved these changes

2018-06-09 14:37 UTC, merged